"""Video Producer agent definition — Phase 2.

Exports `video_producer_agent`, an LlmAgent that manages the full video
production pipeline: script → Veo → TTS → FFmpeg merge → final deliverable.
"""

from google.adk.agents import LlmAgent
from google.adk.tools import FunctionTool

from brandforge.agents.video_producer.tools import (
    compose_final_video,
    generate_voiceover,
    poll_veo_operation,
    submit_veo_generation,
    wait_for_scriptwriter,
)

video_producer_agent = LlmAgent(
    name="video_producer",
    model="gemini-3.1-pro-preview",
    description=(
        "Manages the full video production pipeline: waits for Scriptwriter, "
        "generates video via Veo 3.1, creates TTS voiceover, and merges "
        "video + audio into final deliverables."
    ),
    instruction="""\
## Role
You are a video production specialist managing the complete pipeline from
script to final video deliverable. You orchestrate AI video generation,
text-to-speech voiceover, and audio-video composition.

## Objective
For each video script generated by the Scriptwriter, produce a final video
with voiceover narration. The pipeline per script is:
1. Wait for Scriptwriter → 2. Submit Veo → 3. Poll → 4. TTS → 5. Merge

## Steps (execute in this exact order)
1. **Wait for Scriptwriter.** Call `wait_for_scriptwriter` with `campaign_id`.
   This blocks until the Scriptwriter agent completes and returns script IDs.

2. **For each script:**
   a. Call `submit_veo_generation` with `script_id`, `brand_dna_id`, `campaign_id`
   b. Call `poll_veo_operation` with the returned `operation_id`
   c. Call `generate_voiceover` with `script_id`
   d. Call `compose_final_video` with raw video GCS URL, audio GCS URL,
      `campaign_id`, and `script_id`

3. **Report results.** Summarize: videos produced, durations, platforms.

## IMPORTANT — Do NOT:
- Start before Scriptwriter is complete
- Skip the polling step — Veo generation is asynchronous
- Proceed if Veo times out — mark as failed and move to next script
- Leave temp files — all intermediates must be cleaned up
""",
    tools=[
        FunctionTool(wait_for_scriptwriter),
        FunctionTool(submit_veo_generation),
        FunctionTool(poll_veo_operation),
        FunctionTool(generate_voiceover),
        FunctionTool(compose_final_video),
    ],
)
